export interface JournalPrompt {
  id: number;
  text: string;
}

export const prompts: JournalPrompt[] = [
  // Self-Reflection
  { id: 1, text: "What is something you've been avoiding, and what's one small step you can take to face it today?" },
  { id: 2, text: "Describe a moment this week when you felt genuinely happy or at peace. What were the circumstances?" },
  { id: 3, text: "What is a belief you hold that you haven't questioned in a while? What might be an alternative perspective?" },
  { id: 4, text: "If you could give your younger self one piece of advice, what would it be and why?" },
  { id: 5, text: "What activity makes you lose track of time? How can you incorporate more of it into your life?" },
  { id: 6, text: "What does 'success' mean to you, beyond external achievements?" },
  { id: 7, text: "What is a boundary you need to set in your life right now?" },
  { id: 8, text: "What is a quality you admire in others that you'd like to cultivate in yourself?" },
  { id: 9, text: "What are you currently worried about? Can you distinguish between what you can and cannot control?" },
  { id: 10, text: "What is a 'should' that you can let go of today?" },
  { id: 11, text: "How have you grown or changed in the past year?" },
  { id: 12, text: "What is something that is currently draining your energy? How can you address it?" },
  { id: 13, text: "If fear wasn't a factor, what would you be doing differently in your life?" },
  { id: 14, text: "How do you define a meaningful life?" },
  { id: 15, text: "What is something you are proud of, but don't often share?" },
  { id: 16, text: "Write about a time you felt truly understood by someone." },
  { id: 17, text: "What is a piece of media (book, movie, song) that has deeply influenced you? Why?" },
  { id: 18, text: "What is one assumption you've made about someone that turned out to be wrong?" },
  { id: 19, text: "In what area of your life are you holding back? What are you afraid of?" },
  { id: 20, text: "Describe your ideal day from start to finish. What makes it ideal?" },
  { id: 21, text: "What is a recurring thought pattern you'd like to change?" },
  { id: 22, text: "When do you feel most like your authentic self?" },
  { id: 23, text: "What is your relationship with change? Do you resist it or embrace it?" },
  { id: 24, text: "If you had to describe your current life chapter with a title, what would it be?" },
  { id: 25, text: "What lesson took you the longest to learn?" },
  { id: 26, text: "What do you need more of in your life right now? What do you need less of?" },
  { id: 27, text: "Write about a time you surprised yourself." },
  { id: 28, text: "What is a simple thing that brings you comfort?" },
  { id: 29, text: "How do you practice self-compassion?" },
  { id: 30, text: "What are your core values, and are you living in alignment with them?" },
  { id: 31, text: "What does your intuition tell you about a current situation?" },
  { id: 32, text: "If you wrote a letter to your body, what would you say?" },
  { id: 33, text: "What is a mistake you keep repeating? Why do you think that is?" },
  { id: 34, text: "What is a conversation you need to have but have been putting off?" },
  { id: 35, text: "Describe a moment you felt a strong sense of belonging." },
  { id: 36, text: "What is a personal project you've been dreaming of? What's the first step?" },
  { id: 37, text: "How do you want to be remembered by others?" },
  { id: 38, text: "What is an outdated version of yourself you need to let go of?" },
  { id: 39, text: "What is a risk you took that paid off?" },
  { id: 40, text: "What does 'home' feel like to you?" },

  // Gratitude
  { id: 41, text: "What are you most grateful for right now, big or small?" },
  { id: 42, text: "Who is someone who has had a positive impact on your life? Write a thank you note to them (you don't have to send it)." },
  { id: 43, text: "What is a compliment you've received that has stayed with you? Why did it mean so much?" },
  { id: 44, text: "Describe an act of kindness you witnessed or performed recently." },
  { id: 45, text: "What is a simple pleasure that you often overlook?" },
  { id: 46, text: "What technology are you grateful for and why?" },
  { id: 47, text: "Think of a person who has challenged you. What did you learn from them?" },
  { id: 48, text: "What aspect of nature are you most grateful for today?" },
  { id: 49, text: "What is a part of your daily routine that you are thankful for?" },
  { id: 50, text: "What skill or talent do you possess that you are grateful for?" },
  { id: 51, text: "What is a difficult experience from your past that you are now grateful for?" },
  { id: 52, text: "Describe a piece of art (music, painting, book) that you are grateful exists." },
  { id: 53, text: "What is a food or meal that you are truly grateful for?" },
  { id: 54, text: "What is something beautiful you saw today?" },
  { id: 55, text: "Who in your life makes you feel safe and supported?" },
  { id: 56, text: "What is a challenge you overcame that you're now grateful for the strength it gave you?" },
  { id: 57, text: "What is a modern convenience you couldn't imagine living without?" },
  { id: 58, text: "What is a happy memory you are grateful for?" },
  { id: 59, text: "What aspect of your health are you most grateful for today?" },
  { id: 60, text: "What is an opportunity you were given that you are thankful for?" },
  { id: 61, text: "Who is a public figure or artist that you are grateful for?" },
  { id: 62, text: "What is a simple thing about the place you live that you appreciate?" },
  { id: 63, text: "Write about a pet or animal that has brought you joy." },
  { id: 64, text: "What is a tradition (family or personal) that you are grateful for?" },
  { id: 65, text: "What is something you learned recently that you're thankful for?" },
  { id: 66, text: "Who made you smile today?" },
  { id: 67, text: "What is a goal you achieved that you are grateful for the journey?" },
  { id: 68, text: "What is a freedom you have that you are grateful for?" },
  { id: 69, text: "What is a character trait you have that you are thankful for?" },
  { id: 70, text: "What is a challenge that helped you discover your own resilience?" },
  { id: 71, text: "Who is a mentor or teacher you are grateful for?" },
  { id: 72, text: "What is a sensory experience (a smell, a taste, a sound) you are grateful for?" },
  { id: 73, text: "What is a book that changed your perspective?" },
  { id: 74, text: "What is a place in your home that brings you peace?" },
  { id: 75, text: "What is a piece of good news you heard recently?" },
  { id: 76, text: "What is a memory of laughter you cherish?" },
  { id: 77, text: "What is something you own that you are deeply grateful for?" },
  { id: 78, text: "What is a song that always lifts your spirits?" },
  { id: 79, text: "What is a way you have been able to help someone else?" },
  { id: 80, text: "What is a truth you are grateful to know?" },

  // Productivity & Goals
  { id: 81, text: "What is one thing you could do today to move closer to a long-term goal?" },
  { id: 82, text: "What is your most important task for tomorrow? Why is it important?" },
  { id: 83, text: "What is a distraction you can eliminate this week to improve your focus?" },
  { id: 84, text: "Describe your ideal productive day. What does it look and feel like?" },
  { id: 85, text: "What is one goal you've been putting off? What's the smallest possible first step?" },
  { id: 86, text: "What system or routine could you create to make a recurring task easier?" },
  { id: 87, text: "When you look back on this week, what is the one thing you want to have accomplished?" },
  { id: 88, text: "What is a 'good enough' decision you can make right now instead of waiting for a 'perfect' one?" },
  { id: 89, text: "How can you better align your daily actions with your long-term vision?" },
  { id: 90, text: "What is a skill you'd love to learn? What's stopping you?" },
  { id: 91, text: "Think about your goals. What is one small action you can take this week to move closer to one of them?" },
  { id: 92, text: "What does your ideal work-life balance look like?" },
  { id: 93, text: "What is a task you can delegate or automate?" },
  { id: 94, text: "Review your goals. Are they still relevant? Do they need to be adjusted?" },
  { id: 95, text: "How can you celebrate your progress, no matter how small?" },
  { id: 96, text: "What is a resource (a person, a book, a tool) that could help you with your current goals?" },
  { id: 97, text: "What is one thing you can say 'no' to this week to protect your time and energy?" },
  { id: 98, text: "What is your biggest time-waster and how can you reduce it?" },
  { id: 99, text: "Break down a large goal into smaller, manageable steps." },
  { id: 100, text: "What will you do to recharge after a productive day?" },
  { id: 101, text: "What is a fear that is holding you back from pursuing a goal?" },
  { id: 102, text: "How do you define 'productivity' for yourself? Is it just about getting things done?" },
  { id: 103, text: "What is the environment you need to do your best work?" },
  { id: 104, text: "What is a habit you could start that would have the biggest positive impact on your goals?" },
  { id: 105, text: "What is a past success you can draw motivation from?" },
  { id: 106, text: "What is a potential obstacle for your goal and how can you plan for it?" },
  { id: 107, text: "Who can you ask for help or support with your goals?" },
  { id: 108, text: "What is a reward you can give yourself for reaching a milestone?" },
  { id: 109, text: "What is one task you can complete in the next 25 minutes?" },
  { id: 110, text: "How can you make your work more enjoyable or meaningful?" },
  { id: 111, text: "What did you learn from your to-do list yesterday?" },
  { id: 112, text: "What is your 'why'? What is the deep reason behind your most important goal?" },
  { id: 113, text: "What is a tiny change you can make to your routine for a big impact?" },
  { id: 114, text: "How will you handle interruptions today?" },
  { id: 115, text: "What does 'done' look like for your main task today?" },
  { id: 116, text: "What is one thing you can do to prepare for a successful tomorrow?" },
  { id: 117, text: "What is a professional boundary you need to enforce?" },
  { id: 118, text: "What is a time management technique you could try?" },
  { id: 119, text: "What is a project you are excited to work on? Why?" },
  { id: 120, text: "How will you measure success for this week?" },

  // Challenges & Resilience
  { id: 121, text: "Write about a failure that taught you a valuable lesson. What was the lesson?" },
  { id: 122, text: "Describe a challenge you are currently facing. What strengths can you bring to this situation?" },
  { id: 123, text: "What is a past challenge that made you stronger? How?" },
  { id: 124, text: "How do you cope with feelings of overwhelm?" },
  { id: 125, text: "Write about a time you had to be brave." },
  { id: 126, text: "What is a criticism you received that was hard to hear but ultimately helpful?" },
  { id: 127, text: "How can you reframe a current challenge as an opportunity?" },
  { id: 128, text: "What is a supportive phrase you can tell yourself when you're struggling?" },
  { id: 129, text: "Describe a time you bounced back from a setback." },
  { id: 130, text: "What is one thing you can do to build your resilience?" },
  { id: 131, text: "Who do you turn to for support during difficult times?" },
  { id: 132, text: "What is a fear you have overcome?" },
  { id: 133, text: "How do you deal with uncertainty?" },
  { id: 134, text: "What is a 'worst-case scenario' you're worried about? How likely is it, really?" },
  { id: 135, text: "What does it mean to you to 'fail forward'?" },
  { id: 136, text: "What is a small act of courage you can take today?" },
  { id: 137, text: "How can you be kinder to yourself when you make a mistake?" },
  { id: 138, text: "What is a lesson you learned from a difficult relationship?" },
  { id: 139, text: "What is a time you felt completely out of your comfort zone?" },
  { id: 140, text: "What is your go-to strategy for calming your mind?" },
  { id: 141, text: "What is a strength you discovered in yourself during a tough time?" },
  { id: 142, text: "How do you handle conflict?" },
  { id: 143, text: "What is a story of resilience (your own or someone else's) that inspires you?" },
  { id: 144, text: "What is one thing you can let go of to reduce your stress?" },
  { id: 145, text: "How do you find hope in difficult situations?" },
  { id: 146, text: "What is a mantra that helps you through tough times?" },
  { id: 147, text: "What is a physical activity that helps you release stress?" },
  { id: 148, text: "Write about a time you forgave someone, or yourself." },
  { id: 149, text: "What is a boundary you're proud of setting?" },
  { id: 150, text: "What is one thing you can control in a situation that feels uncontrollable?" },
  { id: 151, text: "How has a past hardship prepared you for who you are today?" },
  { id: 152, text: "What is a sign that you need to take a break and rest?" },
  { id: 153, text: "How can you find a moment of peace in a chaotic day?" },
  { id: 154, text: "What is a piece of advice you would give to someone facing a similar challenge?" },
  { id: 155, text: "What is a time you asked for help and it made a difference?" },
  { id: 156, text: "How do you stay grounded when things are changing quickly?" },
  { id: 157, text: "What is a difficult truth you have come to accept?" },
  { id: 158, text: "What is a source of strength for you?" },
  { id: 159, text: "How can you show yourself compassion for a past mistake?" },
  { id: 160, text: "What does it mean to be strong, in your own words?" },

  // Mindfulness
  { id: 161, text: "Describe a sound, smell, and sight from your environment right now." },
  { id: 162, text: "Take five deep breaths. Describe how you feel before and after." },
  { id: 163, text: "What are three things you can see from where you are right now? Describe them in detail." },
  { id: 164, text: "Focus on your body. What physical sensations are you aware of?" },
  { id: 165, text: "Describe the taste of your last meal or drink as if you were experiencing it for the first time." },
  { id: 166, text: "What is the weather like right now? Describe it using all your senses." },
  { id: 167, text: "Listen for a sound you don't normally notice. What is it?" },
  { id: 168, text: "How does the ground feel beneath your feet?" },
  { id: 169, text: "Look at your hands. What do you notice about them?" },
  { id: 170, text: "What is the emotion you are feeling right now? Where do you feel it in your body?" },
  { id: 171, text: "Think about your next task. What is the very first physical action you will take?" },
  { id: 172, text: "Describe the feeling of the clothes on your skin." },
  { id: 173, text: "What is the temperature of the air around you?" },
  { id: 174, text: "Observe your thoughts for a minute without judgment, like clouds passing in the sky. What did you notice?" },
  { id: 175, text: "Find an object nearby and describe its color, texture, and shape in detail." },
  { id: 176, text: "What is a small, ordinary moment from today that you can appreciate?" },
  { id: 177, text: "How does your body feel after stretching for one minute?" },
  { id: 178, text: "Listen to a piece of music without doing anything else. What did you hear that you hadn't noticed before?" },
  { id: 179, text: "What is the rhythm of your own breathing right now?" },
  { id: 180, text: "Describe the journey of a sip of water from the glass to your stomach." },
  { id: 181, text: "What is a color you see right now? How many shades of it can you find?" },
  { id: 182, text: "If you had to describe this exact moment in one word, what would it be?" },
  { id: 183, text: "What is a worry you can consciously set aside for the next 10 minutes?" },
  { id: 184, text: "What is a bodily sensation that is pleasant right now (e.g., warmth, comfort)?" },
  { id: 185, text: "Look at something natural - a plant, the sky, a pet. What do you observe?" },
  { id: 186, text: "What is the quality of the light in the room you are in?" },
  { id: 187, text: "Silently name five things you are grateful for in this present moment." },
  { id: 188, text: "How does it feel to simply sit still for one minute without any distractions?" },
  { id: 189, text: "What is a sound that is far away? What is a sound that is very close?" },
  { id: 190, text: "What is the intention you want to set for the next hour?" },
  { id: 191, text: "Gently scan your body from head to toe. What area is holding tension?" },
  { id: 192, text: "What is one thing you can do to be more present in your next conversation?" },
  { id: 193, text: "Describe the sensation of your feet on the floor." },
  { id: 194, text: "What is the most dominant emotion in your mind right now? Name it without judgment." },
  { id: 195, text: "What is a simple task you can do mindfully (e.g., washing hands, making tea)?" },
  { id: 196, text: "What does the air smell like?" },
  { id: 197, text: "Look at the back of your hand. Notice the lines, colors, and textures." },
  { id: 198, text: "What is one beautiful thing in your immediate surroundings?" },
  { id: 199, text: "How does it feel to unclench your jaw and drop your shoulders?" },
  { id: 200, text: "What is the single, most important thing to focus on right now?" }
];
