import { Affirmation } from '../components/AffirmationFormModal';

export const affirmations: Affirmation[] = [
  // Positive Affirmations (100)
  { id: '1', text: 'I am capable of achieving great things.' },
  { id: '2', text: 'I choose to be happy and to love myself today.' },
  { id: '3', text: 'My potential to succeed is infinite.' },
  { id: '4', text: 'I am creating the life of my dreams.' },
  { id: '5', text: 'I am worthy of peace and happiness.' },
  { id: '6', text: 'I embrace change and welcome new opportunities.' },
  { id: '7', text: 'I have the power to overcome any challenge.' },
  { id: '8', text: 'I trust my intuition and make wise decisions.' },
  { id: '9', text: 'I am resilient, strong, and brave.' },
  { id: '10', text: 'I attract positivity and abundance into my life.' },
  { id: '11', text: 'Every day, I am growing and evolving.' },
  { id: '12', text: 'I am in control of my thoughts and emotions.' },
  { id: '13', text: 'I am proud of the person I am becoming.' },
  { id: '14', text: 'I let go of what I cannot change and focus on what I can.' },
  { id: '15', text: 'My mind is filled with positive and nourishing thoughts.' },
  { id: '16', text: 'I am deserving of love, respect, and joy.' },
  { id: '17', text: 'I am confident in my abilities and skills.' },
  { id: '18', text: 'I forgive myself for my past mistakes.' },
  { id: '19', text: 'I have the courage to say no when I need to.' },
  { id: '20', text: 'My body is my home, and I treat it with kindness.' },
  { id: '21', text: 'I am open to receiving all the good life has to offer.' },
  { id: '22', text: 'I release all self-doubt and embrace self-belief.' },
  { id: '23', text: 'I am a magnet for miracles.' },
  { id: '24', text: 'My hard work is paying off.' },
  { id: '25', text: 'I am surrounded by supportive and loving people.' },
  { id: '26', text: 'I make a positive impact on the world around me.' },
  { id: '27', text: 'I am calm, centered, and at peace.' },
  { id: '28', text: 'I celebrate my small victories and progress.' },
  { id: '29', text: 'My possibilities are endless.' },
  { id: '30', text: 'I am grateful for this day and its potential.' },
  { id: '31', text: 'I am enough, just as I am.' },
  { id: '32', text: 'I have the strength to get through any hardship.' },
  { id: '33', text: 'I am becoming a better version of myself every day.' },
  { id: '34', text: 'I am worthy of my dreams.' },
  { id: '35', text: 'I choose to see the good in every situation.' },
  { id: '36', text: 'My creativity is flowing.' },
  { id: '37', text: 'I am focused on my goals and priorities.' },
  { id: '38', text: 'I am letting go of fear and choosing love.' },
  { id: '39', text: 'My heart is open to giving and receiving love.' },
  { id: '40', text: 'I am the architect of my own happiness.' },
  { id: '41', text: 'I am at peace with my past.' },
  { id: '42', text: 'I am excited about the future.' },
  { id: '43', text: 'I am making healthy choices for my mind and body.' },
  { id: '44', text: 'I am a source of inspiration to others.' },
  { id: '45', text: 'My journey is unfolding perfectly.' },
  { id: '46', text: 'I have everything I need to be successful.' },
  { id: '47', text: 'I am worthy of financial stability and abundance.' },
  { id: '48', text: 'I handle stress with grace and ease.' },
  { id: '49', text: 'I am brave enough to be my authentic self.' },
  { id: '50', text: 'I am a powerful creator of my reality.' },
  { id: '51', text: 'I am worthy of rest and rejuvenation.' },
  { id: '52', text: 'I speak my truth with confidence and compassion.' },
  { id: '53', text: 'I am a lifelong learner.' },
  { id: '54', text: 'I find joy in the simple things.' },
  { id: '55', text: 'I am aligned with my purpose.' },
  { id: '56', text: 'I release the need for perfection.' },
  { id: '57', text: 'I am a beacon of light and positivity.' },
  { id: '58', text: 'I am grateful for my unique talents.' },
  { id: '59', text: 'I treat myself with the kindness of a dear friend.' },
  { id: '60', text: 'My voice matters.' },
  { id: '61', text: 'I am capable of creating meaningful connections.' },
  { id: '62', text: 'I am worthy of taking up space.' },
  { id: '63', text: 'I am healing and becoming whole.' },
  { id: '64', text: 'I am the master of my own energy.' },
  { id: '65', text: 'I am blessed with incredible opportunities.' },
  { id: '66', text: 'I am strong enough to set and maintain my boundaries.' },
  { id: '67', text: 'I am proud of my journey and all I have overcome.' },
  { id: '68', text: 'I am open to new ideas and perspectives.' },
  { id: '69', text: 'I am building a beautiful life.' },
  { id: '70', text: 'I am letting my light shine brightly.' },
  { id: '71', text: 'I am a problem-solver.' },
  { id: '72', text: 'I am financially responsible and prosperous.' },
  { id: '73', text: 'I am surrounded by beauty.' },
  { id: '74', text: 'I am a good and compassionate person.' },
  { id: '75', text: 'I am exactly where I need to be.' },
  { id: '76', text: 'I am filled with energy and vitality.' },
  { id: '77', text: 'I am making a difference in the world.' },
  { id: '78', text: 'I am worthy of a life filled with joy and laughter.' },
  { id: '79', text: 'I am grateful for my body and all it does for me.' },
  { id: '80', text: 'I am attracting positive outcomes.' },
  { id: '81', text: 'I am at peace with who I am.' },
  { id: '82', text: 'I am a creative and resourceful individual.' },
  { id: '83', text: 'I am open to feedback and growth.' },
  { id: '84', text: 'I am a great listener.' },
  { id: '85', text: 'I am confident in the path I am taking.' },
  { id: '86', text: 'I am deserving of a fulfilling career.' },
  { id: '87', text: 'I am a loving and supportive partner/friend/family member.' },
  { id: '88', text: 'I am releasing anxiety and embracing calm.' },
  { id: '89', text: 'I am worthy of my own time and attention.' },
  { id: '90', text: 'I am a work in progress, and that is okay.' },
  { id: '91', text: 'I am choosing progress over perfection.' },
  { id: '92', text: 'I am cultivating patience and understanding.' },
  { id: '93', text: 'I am the creator of my own peace.' },
  { id: '94', text: 'I am powerful, loved, and valuable.' },
  { id: '95', text: 'I am attracting the right people into my life.' },
  { id: '96', text: 'I am worthy of celebrating my achievements.' },
  { id: '97', text: 'I am listening to my body\'s needs.' },
  { id: '98', text: 'I am embracing the present moment.' },
  { id: '99', text: 'I am capable of learning and adapting.' },
  { id: '100', text: 'I am ready for a wonderful day.' },

  // Famous Quotes (50)
  { id: '101', text: 'The journey of a thousand miles begins with one step. - Lao Tzu' },
  { id: '102', text: 'Believe you can and you\'re halfway there. - Theodore Roosevelt' },
  { id: '103', text: 'The only way to do great work is to love what you do. - Steve Jobs' },
  { id: '104', text: 'It is never too late to be what you might have been. - George Eliot' },
  { id: '105', text: 'Our greatest glory is not in never falling, but in rising every time we fall. - Confucius' },
  { id: '106', text: 'The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt' },
  { id: '107', text: 'Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill' },
  { id: '108', text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson' },
  { id: '109', text: 'The best way to predict the future is to create it. - Peter Drucker' },
  { id: '110', text: 'You miss 100% of the shots you don\'t take. - Wayne Gretzky' },
  { id: '111', text: 'Act as if what you do makes a difference. It does. - William James' },
  { id: '112', text: 'I have not failed. I\'ve just found 10,000 ways that won\'t work. - Thomas A. Edison' },
  { id: '113', text: 'A person who never made a mistake never tried anything new. - Albert Einstein' },
  { id: '114', text: 'The only impossible journey is the one you never begin. - Tony Robbins' },
  { id: '115', text: 'In the middle of difficulty lies opportunity. - Albert Einstein' },
  { id: '116', text: 'Start where you are. Use what you have. Do what you can. - Arthur Ashe' },
  { id: '117', text: 'The secret of getting ahead is getting started. - Mark Twain' },
  { id: '118', text: 'It does not matter how slowly you go as long as you do not stop. - Confucius' },
  { id: '119', text: 'Everything you’ve ever wanted is on the other side of fear. - George Addair' },
  { id: '120', text: 'Fall seven times and stand up eight. - Japanese Proverb' },
  { id: '121', text: 'The mind is everything. What you think you become. - Buddha' },
  { id: '122', text: 'Turn your wounds into wisdom. - Oprah Winfrey' },
  { id: '123', text: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle' },
  { id: '124', text: 'The purpose of our lives is to be happy. - Dalai Lama' },
  { id: '125', text: 'You must be the change you wish to see in the world. - Mahatma Gandhi' },
  { id: '126', text: 'Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson' },
  { id: '127', text: 'The only thing we have to fear is fear itself. - Franklin D. Roosevelt' },
  { id: '128', text: 'Strive not to be a success, but rather to be of value. - Albert Einstein' },
  { id: '129', text: 'If you want to lift yourself up, lift up someone else. - Booker T. Washington' },
  { id: '130', text: 'What we think, we become. - Buddha' },
  { id: '131', text: 'The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb' },
  { id: '132', text: 'An unexamined life is not worth living. - Socrates' },
  { id: '133', text: 'Either you run the day or the day runs you. - Jim Rohn' },
  { id: '134', text: 'Whether you think you can or you think you can’t, you’re right. - Henry Ford' },
  { id: '135', text: 'The two most important days in your life are the day you are born and the day you find out why. - Mark Twain' },
  { id: '136', text: 'Nothing is impossible, the word itself says \'I\'m possible\'! - Audrey Hepburn' },
  { id: '137', text: 'The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt' },
  { id: '138', text: 'To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde' },
  { id: '139', text: 'It is not in the stars to hold our destiny but in ourselves. - William Shakespeare' },
  { id: '140', text: 'What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar' },
  { id: '141', text: 'If you are not willing to risk the usual you will have to settle for the ordinary. - Jim Rohn' },
  { id: '142', text: 'All our dreams can come true, if we have the courage to pursue them. - Walt Disney' },
  { id: '143', text: 'If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on. - Sheryl Sandberg' },
  { id: '144', text: 'A goal is a dream with a deadline. - Napoleon Hill' },
  { id: '145', text: 'The harder I work, the luckier I get. - Samuel Goldwyn' },
  { id: '146', text: 'Don\'t watch the clock; do what it does. Keep going. - Sam Levenson' },
  { id: '147', text: 'Change your thoughts and you change your world. - Norman Vincent Peale' },
  { id: '148', text: 'Well done is better than well said. - Benjamin Franklin' },
  { id: '149', text: 'Without hustle, talent will only get you so far. - Gary Vaynerchuk' },
  { id: '150', text: 'You can, you should, and if you’re brave enough to start, you will. - Stephen King' },

  // Bible Verses (50)
  { id: '151', text: 'I can do all things through Christ who strengthens me. - Philippians 4:13' },
  { id: '152', text: 'For I know the plans I have for you, declares the Lord. - Jeremiah 29:11' },
  { id: '153', text: 'Be still, and know that I am God. - Psalm 46:10' },
  { id: '154', text: 'The Lord is my shepherd; I shall not want. - Psalm 23:1' },
  { id: '155', text: 'Trust in the Lord with all your heart and lean not on your own understanding. - Proverbs 3:5' },
  { id: '156', text: 'He gives power to the faint, and to him who has no might he increases strength. - Isaiah 40:29' },
  { id: '157', text: 'But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles. - Isaiah 40:31' },
  { id: '158', text: 'For God gave us a spirit not of fear but of power and love and self-control. - 2 Timothy 1:7' },
  { id: '159', text: 'Let all that you do be done in love. - 1 Corinthians 16:14' },
  { id: '160', text: 'I have told you these things, so that in me you may have peace. - John 16:33' },
  { id: '161', text: 'The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness. - Galatians 5:22' },
  { id: '162', text: 'Come to me, all who labor and are heavy laden, and I will give you rest. - Matthew 11:28' },
  { id: '163', text: 'This is the day that the Lord has made; let us rejoice and be glad in it. - Psalm 118:24' },
  { id: '164', text: 'And we know that in all things God works for the good of those who love him. - Romans 8:28' },
  { id: '165', text: 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. - Philippians 4:6' },
  { id: '166', text: 'The steadfast love of the Lord never ceases; his mercies never come to an end. - Lamentations 3:22' },
  { id: '167', text: 'For where your treasure is, there your heart will be also. - Matthew 6:21' },
  { id: '168', text: 'The Lord is my light and my salvation; whom shall I fear? - Psalm 27:1' },
  { id: '169', text: 'A joyful heart is good medicine, but a crushed spirit dries up the bones. - Proverbs 17:22' },
  { id: '170', text: 'Be strong and courageous. Do not be frightened, and do not be dismayed, for the Lord your God is with you wherever you go. - Joshua 1:9' },
  { id: '171', text: 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come. - 2 Corinthians 5:17' },
  { id: '172', text: 'Let the morning bring me word of your unfailing love, for I have put my trust in you. - Psalm 143:8' },
  { id: '173', text: 'Cast all your anxiety on him because he cares for you. - 1 Peter 5:7' },
  { id: '174', text: 'It is for freedom that Christ has set us free. - Galatians 5:1' },
  { id: '175', text: 'The joy of the Lord is your strength. - Nehemiah 8:10' },
  { id: '176', text: 'I have fought the good fight, I have finished the race, I have kept the faith. - 2 Timothy 4:7' },
  { id: '177', text: 'For we walk by faith, not by sight. - 2 Corinthians 5:7' },
  { id: '178', text: 'Love is patient, love is kind. - 1 Corinthians 13:4' },
  { id: '179', text: 'Whatever you do, work heartily, as for the Lord and not for men. - Colossians 3:23' },
  { id: '180', text: 'So do not fear, for I am with you; do not be dismayed, for I am your God. - Isaiah 41:10' },
  { id: '181', text: 'Give thanks in all circumstances; for this is the will of God in Christ Jesus for you. - 1 Thessalonians 5:18' },
  { id: '182', text: 'Blessed are the peacemakers, for they shall be called children of God. - Matthew 5:9' },
  { id: '183', text: 'When I am afraid, I put my trust in you. - Psalm 56:3' },
  { id: '184', text: 'He has made everything beautiful in its time. - Ecclesiastes 3:11' },
  { id: '185', text: 'I am the vine; you are the branches. Whoever abides in me and I in him, he it is that bears much fruit. - John 15:5' },
  { id: '186', text: 'Let your light shine before others, so that they may see your good works and give glory to your Father who is in heaven. - Matthew 5:16' },
  { id: '187', text: 'I praise you, for I am fearfully and wonderfully made. - Psalm 139:14' },
  { id: '188', text: 'Above all else, guard your heart, for everything you do flows from it. - Proverbs 4:23' },
  { id: '189', text: 'If God is for us, who can be against us? - Romans 8:31' },
  { id: '190', text: 'He will wipe away every tear from their eyes. - Revelation 21:4' },
  { id: '191', text: 'My grace is sufficient for you, for my power is made perfect in weakness. - 2 Corinthians 12:9' },
  { id: '192', text: 'Commit your work to the Lord, and your plans will be established. - Proverbs 16:3' },
  { id: '193', text: 'For with God nothing shall be impossible. - Luke 1:37' },
  { id: '194', text: 'Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you. - Ephesians 4:32' },
  { id: '195', text: 'Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you. - Matthew 7:7' },
  { id: '196', text: 'Greater love has no one than this, that someone lay down his life for his friends. - John 15:13' },
  { id: '197', text: 'Delight yourself in the Lord, and he will give you the desires of your heart. - Psalm 37:4' },
  { id: '198', text: 'He heals the brokenhearted and binds up their wounds. - Psalm 147:3' },
  { id: '199', text: 'And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus. - Philippians 4:7' },
  { id: '200', text: 'The grass withers, the flower fades, but the word of our God will stand forever. - Isaiah 40:8' }
];
